### ISSUE TITLE
Make HoleList public or make Heap::extend accept non contiguous areas

### ISSUE THREAD

**Issue by MarcoCicognani** [phil-opp/linked-list-allocator#40]
Hi, I'm a follower of your work, that is excellent.
I currently develop a Rust OS based on the crates and the blog you wrote, but the user space allocation memory model doesn't follow the classic sbrk-like schema, instead uses a mmap oriented one.
So i gently request you to allow linked_list_allocator accept non contiguous areas in `Heap::extend(by: usize)` as extensions simply modifying the method to `Heap::extend(start_addr: usize, size: usize)`.
Otherwise you could make public the `HoleList` module to allow external uses.

best regards Marco Cicognani

**Comment by MarcoCicognani** [comment]
I know that with an `Heap::extend_with_region(start_addr: usize, size: usize)` `top` make no more sense, but in my specific case it doesn't matter

**Comment by phil-opp** [comment]
Resolved in https://github.com/phil-opp/linked-list-allocator/pull/47
