### ISSUE TITLE
use_spin feature requires nightly. Is this intentional?

### ISSUE THREAD

**Issue by dylanede** [phil-opp/linked-list-allocator#45]
The readme suggests that the `use_spin` feature does not require nightly, however it enables the `nightly` feature of spinning_top, which means that it relies on nightly and the `const_fn` rustc unstable feature. Is this an error in the readme, or in the enabling of the `nightly` feature on `spinning_top`?

**Comment by phil-opp** [comment]
Thanks for reporting! This is not intentional and compiling on stable should be checked on our CI normally, but it seems like the `rust-toolchain` file in this repo accidentally caused all tests to run on nightly. I'll look into it.
