### ISSUE TITLE
In recent versions, crate depends on alloc

### ISSUE THREAD

**Issue by Redrield** [phil-opp/linked-list-allocator#5]
Since release 0.3.0 of the crate, this library depends on alloc, and requires types from it to fill functions. Because alloc requires an allocator, you can't link it in any crate marked with #![allocator], so it all breaks down.

Fix: Remove dependency on alloc by replacing Layout parameters with size, and align usize parameters, like they were in v0.2.7

**Comment by phil-opp** [comment]
The allocator API was changed a few days ago. The `#![allocator]` attribute is gone now. Instead, a global allocator is now defined through the `Alloc` trait and the `#[global_allocator]` attribute. See #4 for more details.

If you update your nightly version, you will need to use the new API, so I decided to adjust this crate. If you want to stay on an older nightly, you can just keep using v0.2.7.

**Comment by Redrield** [comment]
Alright, I don't really keep up with changes like this, cause I'm normally not one to use unstable features. Thanks!
