### ISSUE TITLE
Can't see the documentation of this crate on docs.rs

### ISSUE THREAD

**Issue by toku-sa-n** [phil-opp/linked-list-allocator#51]
I'm not sure this is a suitable place to notice this, so forgive me if this is not.

As the title says, we can't view [the documentation of v0.9.0](https://docs.rs/crate/linked_list_allocator/0.9.0) because of a build error. ([log](https://docs.rs/crate/linked_list_allocator/0.9.0/builds/383672)). We can see [the v0.8.11 one](https://docs.rs/crate/linked_list_allocator/0.8.11) instead.

**Comment by phil-opp** [comment]
Thanks for reporting! Looks like docs.rs still used an older nightly when the build was done. I opened https://github.com/rust-lang/docs.rs/issues/1401 to request a rebuild.

**Comment by toku-sa-n** [comment]
Thank you!

**Comment by phil-opp** [comment]
This was fixed.
